DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS gate_results CASCADE;
DROP TABLE IF EXISTS gates CASCADE;
DROP TABLE IF EXISTS baselines CASCADE;
DROP TABLE IF EXISTS runs CASCADE;
DROP TABLE IF EXISTS scripts CASCADE;
DROP TABLE IF EXISTS projects CASCADE;

DROP TYPE IF EXISTS gate_result_status;
DROP TYPE IF EXISTS gate_policy;
DROP TYPE IF EXISTS run_status;
DROP TYPE IF EXISTS run_engine;
DROP TYPE IF EXISTS run_mode;
DROP TYPE IF EXISTS authoring_mode;

DROP FUNCTION IF EXISTS update_updated_at();
